version: '3'

# docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.13.4
# docker build -t lasearchapi -f Dockerfile  .

                # docker run -d  -p 7010:80 centralmodel:latest
                # docker run -d  -p 7020:80 centralmodel:latest

services:
  squire6010:
    image: centralmodel:latest
    ports:
      - '6010:80'
  squire6020:
    image: centralmodel:latest
    ports:
      - '6020:80'